export enum FromFieldIconEnum {
  patient = 'patient',
  mail = 'mail',
  phone = 'phone',
  phoneDisabled = 'phone_disabled',
  smartphone = 'smartphone',
  recordVoiceOver = 'record_voice_over',
  apartment = 'apartment',
  home = 'home',
  house = 'house',
  locationCity = 'location_city',
  localPostOffice = 'local_post_office',
  faHashtag = 'fa-hashtag',
  faFireAlt = 'fa-hashtag',
  checkCircle = 'check_circle',
  build = 'build',
  warning = 'warning',
  looks_one = 'looks_one',
  check_box_outline_blank = 'check_box_outline_blank',
  check_box = 'check_box',
  euro = 'euro',
  faPercent = 'fa-percent',
  event = 'event',
  unpublished = 'unpublished',
  none = 'none',

}
